matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      python: 3.6
      sudo: true
      
    - os: linux
      dist: xenial
      python: 3.6      
      sudo: true
    
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
